export const GET_ALL_COUNTRY_LIST_REQUEST = "GET_ALL_COUNTRY_LIST_REQUEST";
export const GET_ALL_COUNTRY_LIST_SUCCESS = "GET_ALL_COUNTRY_LIST_SUCCESS";
export const GET_ALL_COUNTRY_LIST_ERROR = "GET_ALL_COUNTRY_LIST_ERROR";
